In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

In [2]:
df = pd.read_csv("../data/raw/youtube_dataset.csv")

In [3]:
df.head()

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,view_count,like_count,comment_count,thumbnail_url,channel_description,country,subscriber_count,video_count
0,sxQnkMfp_6M,హైదరాబాద్‌ KBR పార్క్‌లో భారీ కొండచిలువ | Huge...,హైదరాబాద్‌ KBR పార్క్‌లో భారీ కొండచిలువ | Huge...,2014-03-29T06:02:22Z,UCDKjhgRoPF1CQk7HluMz23A,Mahaa News,25,"['Huge Python at Hyderabad KBR Park', 'Hyderab...",PT1M40S,3787894875,273.0,41.0,https://i.ytimg.com/vi/sxQnkMfp_6M/hqdefault.jpg,\nWatch : \nMahaa News Live is a 24-hour Telug...,IN,2860000,387957
1,_uQrJ0TkZlc,Python Full Course for Beginners,"Learn Python for AI, machine learning, and web...",2014-10-07T00:40:53Z,UCWv7vMbMWH4-V0ZXdmDpPBA,Programming with Mosh,27,"['python tutorial', 'python', 'python for begi...",PT6H14M7S,275352417,1261583.0,62840.0,https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg,"Hi! I'm Mosh 👋, a software engineer with over ...",US,5110000,246
2,q2-pnQffZik,Learn Python for FREE in 2025,Learn Python for FREE in 2025 #coding #compsci...,2020-06-18T00:50:20.154391Z,UC7zZ2-Q_oxbUaoMVL0z51wg,Sajjaad Khader,27,NaN,PT22S,61209740,30269.0,233.0,https://i.ytimg.com/vi/q2-pnQffZik/hqdefault.jpg,Teaching you how to break into tech in 2026. \...,US,323000,1320
3,yZl5FJ3ChkI,Python Roadmap For Beginners (Step By Step),"If I was a beginner learning to code, I would ...",2023-07-19T04:42:59.663153Z,UCgKFOz_KrMbmypWrawtzDQg,Erik Cupsa,28,NaN,PT53S,19270503,28242.0,141.0,https://i.ytimg.com/vi/yZl5FJ3ChkI/hqdefault.jpg,Welcome to the channel!\n\nThis is where I doc...,NaN,108000,744
4,K5KVEU3aaeQ,Python Full Course for Beginners,Master Python from scratch 🚀 No fluff—just cle...,2014-10-07T00:40:53Z,UCWv7vMbMWH4-V0ZXdmDpPBA,Programming with Mosh,27,"['python full course', 'python full course for...",PT2H2M21S,275352417,159378.0,4170.0,https://i.ytimg.com/vi/K5KVEU3aaeQ/hqdefault.jpg,"Hi! I'm Mosh 👋, a software engineer with over ...",US,5110000,246

In [4]:
df.shape

(97, 17)

In [5]:
df.columns

Index(['video_id', 'title', 'description', 'published_at', 'channel_id',
       'channel_title', 'category_id', 'tags', 'duration', 'view_count',
       'like_count', 'comment_count', 'thumbnail_url', 'channel_description',
       'country', 'subscriber_count', 'video_count'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             97 non-null     str
 1   title                97 non-null     str
 2   description          93 non-null     str
 3   published_at         97 non-null     str
 4   channel_id           97 non-null     str
 5   channel_title        97 non-null     str
 6   category_id          97 non-null     int64
 7   tags                 75 non-null     str
 8   duration             97 non-null     str
 9   view_count           97 non-null     int64
 10  like_count           94 non-null     float64
 11  comment_count        96 non-null     float64
 12  thumbnail_url        97 non-null     str
 13  channel_description  94 non-null     str
 14  country              90 non-null     str
 15  subscriber_count     97 non-null     int64
 16  video_count          97 non-null     int64
dtypes: float64(2), int64(4), str(11)
memory usage: 283.0 KB

In [7]:
df.isnull().sum()

video_id                0
title                   0
description             4
published_at            0
channel_id              0
channel_title           0
category_id             0
tags                   22
duration                0
view_count              0
like_count              3
comment_count           1
thumbnail_url           0
channel_description     3
country                 7
subscriber_count        0
video_count             0
dtype: int64

In [8]:
df.describe

<bound method NDFrame.describe of        video_id                                              title  \
0   sxQnkMfp_6M  హైదరాబాద్‌ KBR పార్క్‌లో భారీ కొండచిలువ | Huge...
1   _uQrJ0TkZlc                   Python Full Course for Beginners
2   q2-pnQffZik                      Learn Python for FREE in 2025
3   yZl5FJ3ChkI        Python Roadmap For Beginners (Step By Step)
4   K5KVEU3aaeQ                   Python Full Course for Beginners
..          ...                                                ...
92  alfdI7S6wCY  MIT Introduction to Deep Learning (2025) | 6.S191
93  PopKlyqTPAI       AI vs ML vs DL vs DS: What's the Difference?
94  V5bulkUiKeE  Difference between machine learning and Deep l...
95  PeMlggyqz0Y          Machine Learning Explained in 100 Seconds
96  zfiSAzpy9NM  Simple explanation of convolutional neural net...

                                          description  \
0   హైదరాబాద్‌ KBR పార్క్‌లో భారీ కొండచిలువ | Huge...
1   Learn Python for AI, machine learning, and web...
2   Learn Python for FREE in 2025 #coding #compsci...
3   If I was a beginner learning to code, I would ...
4   Master Python from scratch 🚀 No fluff—just cle...
..                                                ...
92  MIT Introduction to Deep Learning 6.S191: Lect...
93  AI vs ML vs DL vs DS: What's the Difference?\n...
94                                                NaN
95  Machine Learning is the process of teaching a ...
96  Want to map your data analysis process clearly...

                   published_at                channel_id  \
0          2014-03-29T06:02:22Z  UCDKjhgRoPF1CQk7HluMz23A
1          2014-10-07T00:40:53Z  UCWv7vMbMWH4-V0ZXdmDpPBA
2   2020-06-18T00:50:20.154391Z  UC7zZ2-Q_oxbUaoMVL0z51wg
3   2023-07-19T04:42:59.663153Z  UCgKFOz_KrMbmypWrawtzDQg
4          2014-10-07T00:40:53Z  UCWv7vMbMWH4-V0ZXdmDpPBA
..                          ...                       ...
92         2009-10-23T18:42:38Z  UCtslD4DGH6PKyG_1gFAX7sg
93         2015-06-11T15:27:03Z  UC0RhatS1pyxInC00YKjjBqQ
94         2018-01-05T10:31:14Z  UCjfZ_7-nqUolqXkOD4WyP4A
95         2017-04-07T18:17:23Z  UCsBjURrPoezykLs9EqgamOA
96         2015-11-07T17:29:46Z  UCh9nVJoWXmFb7sLApWGcLPQ

            channel_title  category_id  \
0              Mahaa News           25
1   Programming with Mosh           27
2          Sajjaad Khader           27
3              Erik Cupsa           28
4   Programming with Mosh           27
..                    ...          ...
92        Alexander Amini           28
93          GeeksforGeeks           27
94        Computer Mentor           27
95               Fireship           28
96             codebasics           27

                                                 tags   duration  view_count  \
0   ['Huge Python at Hyderabad KBR Park', 'Hyderab...    PT1M40S  3787894875
1   ['python tutorial', 'python', 'python for begi...  PT6H14M7S   275352417
2                                                 NaN      PT22S    61209740
3                                                 NaN      PT53S    19270503
4   ['python full course', 'python full course for...  PT2H2M21S   275352417
..                                                ...        ...         ...
92  ['deep learning', 'mit', 'artificial intellige...  PT1H9M26S    16245286
93  ['AIvsMLvsDLvsDS', 'ArtificialIntelligence', '...     PT1M2S   202503086
94                                                NaN      PT15S     2053076
95  ['webdev', 'app development', 'lesson', 'tutor...    PT2M35S   716381510
96  ['what is cnn in deep learning', 'what is cnn ...   PT23M54S   162927119

    like_count  comment_count  \
0        273.0           41.0
1    1261583.0        62840.0
2      30269.0          233.0
3      28242.0          141.0
4     159378.0         4170.0
..         ...            ...
92     23242.0          432.0
93     73792.0          289.0
94       470.0            7.0
95     39096.0          669.0
96     29134.0          832.0

                                       thumbnail_url  \
0   https://i.ytimg.com/vi/sxQnkMfp_6M/hqdefault.jpg
1   https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg
2   https://i.ytimg.com/vi/q2-pnQffZik/hqdefault.jpg
3   https://i.ytimg.com/vi/yZl5FJ3ChkI/hqdefault.jpg
4   https://i.ytimg.com/vi/K5KVEU3aaeQ/hqdefault.jpg
..                                               ...
92  https://i.ytimg.com/vi/alfdI7S6wCY/hqdefault.jpg
93  https://i.ytimg.com/vi/PopKlyqTPAI/hqdefault.jpg
94  https://i.ytimg.com/vi/V5bulkUiKeE/hqdefault.jpg
95  https://i.ytimg.com/vi/PeMlggyqz0Y/hqdefault.jpg
96  https://i.ytimg.com/vi/zfiSAzpy9NM/hqdefault.jpg

                                  channel_description country  \
0   \nWatch : \nMahaa News Live is a 24-hour Telug...      IN
1   Hi! I'm Mosh 👋, a software engineer with over ...      US
2   Teaching you how to break into tech in 2026. \...      US
3   Welcome to the channel!\n\nThis is where I doc...     NaN
4   Hi! I'm Mosh 👋, a software engineer with over ...      US
..                                                ...     ...
92                                                NaN     NaN
93  Welcome to the Official Channel of GeekforGeek...      IN
94  Assalam-o-Alaikum Everyone!\nIts my YouTube ch...     NaN
95  High-intensity ⚡ code tutorials and tech news ...      US
96  I am Dhaval Patel, an AI professional with 14 ...      US

    subscriber_count  video_count
0            2860000       387957
1            5110000          246
2             323000         1320
3             108000          744
4            5110000          246
..               ...          ...
92            355000          100
93           1220000         4115
94              4700          175
95           4230000          825
96           1550000         1244

[97 rows x 17 columns]>

In [9]:
(df.isnull().sum() / len(df)) * 100

video_id                0.000000
title                   0.000000
description             4.123711
published_at            0.000000
channel_id              0.000000
channel_title           0.000000
category_id             0.000000
tags                   22.680412
duration                0.000000
view_count              0.000000
like_count              3.092784
comment_count           1.030928
thumbnail_url           0.000000
channel_description     3.092784
country                 7.216495
subscriber_count        0.000000
video_count             0.000000
dtype: float64

In [15]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
91    False
92    False
93    False
94    False
96    False
Length: 94, dtype: bool

In [16]:
for col in df.columns:
    print(col, df[col].nunique())

video_id 94
title 93
description 90
published_at 60
channel_id 60
channel_title 60
category_id 5
tags 72
duration 89
view_count 60
like_count 91
comment_count 86
thumbnail_url 94
channel_description 57
country 6
subscriber_count 60
video_count 58

In [17]:
df.dtypes

video_id                   str
title                      str
description                str
published_at               str
channel_id                 str
channel_title              str
category_id              int64
tags                       str
duration                   str
view_count               int64
like_count             float64
comment_count          float64
thumbnail_url              str
channel_description        str
country                    str
subscriber_count         int64
video_count              int64
dtype: object

In [19]:
df.describe(include="all")

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,view_count,like_count,comment_count,thumbnail_url,channel_description,country,subscriber_count,video_count
count,94,94,90,94,94,94,94.000000,72,94,9.400000e+01,9.100000e+01,93.000000,94,91,87,9.400000e+01,94.000000
unique,94,93,90,60,60,60,NaN,72,89,NaN,NaN,NaN,94,57,6,NaN,NaN
top,sxQnkMfp_6M,Python Full Course for Beginners,హైదరాబాద్‌ KBR పార్క్‌లో భారీ కొండచిలువ | Huge...,2014-12-16T21:18:48Z,UC8butISFwT-Wl7EV0hUK0BQ,freeCodeCamp.org,NaN,"['Huge Python at Hyderabad KBR Park', 'Hyderab...",PT16S,NaN,NaN,NaN,https://i.ytimg.com/vi/sxQnkMfp_6M/hqdefault.jpg,"Learn math, programming, and computer science ...",US,NaN,NaN
freq,1,2,1,8,8,8,NaN,1,3,NaN,NaN,NaN,1,8,52,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,26.797872,NaN,NaN,3.810969e+08,8.491480e+04,3119.612903,NaN,NaN,NaN,3.275544e+06,7872.670213
std,NaN,NaN,NaN,NaN,NaN,NaN,1.249342,NaN,NaN,5.816902e+08,1.967828e+05,10331.069412,NaN,NaN,NaN,3.851716e+06,40521.674150
min,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,NaN,NaN,2.551120e+05,6.800000e+01,0.000000,NaN,NaN,NaN,2.930000e+03,39.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,1.873231e+07,3.148000e+03,53.000000,NaN,NaN,NaN,1.382500e+05,240.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,1.629271e+08,2.557600e+04,299.000000,NaN,NaN,NaN,1.510000e+06,1014.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,5.616530e+08,7.128200e+04,1344.000000,NaN,NaN,NaN,5.110000e+06,2875.250000
max,NaN,NaN,NaN,NaN,NaN,NaN,28.000000,NaN,NaN,3.787895e+09,1.261583e+06,62840.000000,NaN,NaN,NaN,1.320000e+07,387957.000000